import { brandMark, faviconLink } from '../brand.js';
import type { ProviderView } from '../provider-store.js';
import { provider as providerSpec, providerCatalog, providerNames } from '../providers/catalog.js';
export const esc = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[c]!);
export const names = Object.fromEntries(providerNames.map(n => [n, providerCatalog[n].label])) as Record<string,string>;
const icons = Object.fromEntries(providerNames.map(n => [n, providerCatalog[n].icon])) as Record<string,string>;
const badge = (text: string, tone = '') => `<span class="badge ${tone}">${esc(text)}</span>`;
const navIcon = (key: string) => {
  const paths: Record<string,string> = {
    overview:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
    providers:'<path d="M8 3v4m8-4v4M6 7h12v4a6 6 0 0 1-12 0V7zm6 10v4"/>',
    projects:'<circle cx="8" cy="8" r="5"/><path d="m11.5 11.5 9 9m-3-3 3-3m-6 0 3-3"/>',
    test:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="m7 9 3 3-3 3m6 0h4"/>',
    guide:'<path d="M12 5v16M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2z"/>',
    connections:'<path d="m10 13 4-4m-5 7-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 0 2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',
    activity:'<path d="M8 3h12v18H4V3h4m0 5h8m-8 4h8m-8 4h5"/>',
  };
  return `<svg class="nav-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[key] || paths.overview}</svg>`;
};
function accountControls(email: string) {
  const avatar = esc((email.split('@')[0] || 'AD').slice(0,2).toUpperCase());
  const icon = (path: string) => `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
  return `<div class="sidebar-bottom"><details class="account-menu"><summary aria-label="打开账号菜单"><span class="account-avatar" translate="no">${avatar}</span><span class="account-name" translate="no">${esc(email)}</span></summary><div class="account-popover"><div class="account-profile"><span class="account-avatar" translate="no">${avatar}</span><span class="account-name" translate="no">${esc(email)}</span></div><button type="button" class="account-action" data-dialog="account-settings">${icon('<path d="m9 3-1 3-3 1v4l-2 1 2 3 3 1 1 3h4l1-3 3-1 2-3-2-1V7l-3-1-1-3Z"/><circle cx="11" cy="11" r="3"/>')}设置</button><form data-api="/admin/api/logout" data-redirect="/admin/login"><button type="submit" class="account-action">${icon('<path d="M9 4H4v16h5m5-13 5 5-5 5M8 12h11"/>')}退出登录</button></form></div></details></div>`;
}
function accountSettings(email: string) {
  const icon = (path: string) => `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
  const icons = {account:icon('<circle cx="10" cy="8" r="3"/><path d="M4 20v-2a6 6 0 0 1 12 0v2m3-10v6m-3-3h6"/>'),general:icon('<circle cx="12" cy="12" r="9"/><circle cx="8" cy="10" r=".5"/><circle cx="12" cy="7" r=".5"/><circle cx="16" cy="10" r=".5"/><path d="M12 21v-5h5"/>'),about:icon('<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>')};
  const themes = [ ['light','浅色',icon('<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>')], ['dark','深色',icon('<path d="M20 14A9 9 0 0 1 10 4a9 9 0 1 0 10 10Z"/>')], ['system','跟随系统',icon('<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M12 17v4m-4 0h8"/>')] ];
  return `<dialog id="account-settings" aria-label="设置"><div class="settings-layout"><aside class="settings-nav"><p>用户</p><div role="tablist" aria-label="设置分类" aria-orientation="vertical">${(['account','general','about'] as const).map((key,i)=>`<button type="button" role="tab" id="settings-tab-${key}" aria-controls="settings-${key}" aria-selected="${key==='general'}" tabindex="${key==='general'?0:-1}" data-settings-tab="${key}">${icons[key]}${['账户','通用','关于'][i]}</button>`).join('')}</div></aside><div class="settings-content"><button type="button" class="settings-close" data-close aria-label="关闭设置">×</button><section id="settings-account" role="tabpanel" aria-labelledby="settings-tab-account" hidden><h2>账户</h2><p class="settings-subtitle">管理你的管理员账号和登录密码。</p><div class="settings-account"><span class="tiny">管理员账号</span><strong translate="no">${esc(email)}</strong></div><h3>修改密码</h3><p>保存后会退出所有登录会话，请使用新密码重新登录。</p><form data-api="/admin/api/account/password" data-redirect="/admin/login"><label>当前密码<input type="password" name="current_password" autocomplete="current-password" required maxlength="256"></label><label>新密码<input type="password" name="new_password" autocomplete="new-password" required minlength="12" maxlength="256"><span class="help">12–256 个字符。</span></label><label>确认新密码<input type="password" name="confirm_password" autocomplete="new-password" required minlength="12" maxlength="256"></label><p class="form-error" role="alert" hidden></p><div class="dialog-actions"><button type="button" class="button secondary" data-close>取消</button><button type="submit" class="button">保存密码</button></div></form></section><section id="settings-general" role="tabpanel" aria-labelledby="settings-tab-general"><h2>通用</h2><p class="settings-subtitle">外观与当前设备偏好设置。</p><div class="settings-card"><h3>主题</h3><p>选择控制台配色。跟随系统会使用操作系统设置。</p><div class="theme-options" role="group" aria-label="主题">${themes.map(([value,label,glyph])=>`<button type="button" data-theme-choice="${value}" aria-pressed="false">${glyph}<span>${label}</span></button>`).join('')}</div></div><div class="settings-card"><h3>界面语言</h3><p>选择控制台使用的界面语言。</p><div class="language-options" role="group" aria-label="界面语言"><button type="button" data-language-choice="en" aria-pressed="true" translate="no">English</button><button type="button" data-language-choice="zh-CN" aria-pressed="false" translate="no">简体中文</button></div></div></section><section id="settings-about" role="tabpanel" aria-labelledby="settings-tab-about" hidden><h2>关于</h2><p class="settings-subtitle">Connany · Agent 连接器服务</p><div class="settings-card">${brandMark}<h3>连接工具与用户数据</h3><p>统一管理账号授权、连接与凭证，让 Agent 在用户授权范围内使用工具。</p><a href="/admin/guide">Agent 接入文档 ↗</a></div></section></div></div></dialog>`;
}
export function layout(title: string, active: string, email: string, csrf: string, content: string) {
  const items = [['overview','/admin','总览'],['providers','/admin/connectors','连接器'],['projects','/admin/keys','API Keys'],['guide','/docs','Docs']];
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="csrf-token" content="${esc(csrf)}"><title>${esc(title)} · Connany</title>${faviconLink}<script src="/admin/assets/admin-preferences.js"></script><link rel="stylesheet" href="/admin/assets/admin.css"><script src="/admin/assets/admin-i18n.js" defer></script><script src="/admin/assets/admin.js" defer></script></head><body class="${active === 'login' ? 'login-body' : ''}">${active === 'login' ? '' : `<aside class="sidebar"><a href="/admin" class="brand">${brandMark} connany</a><span class="workspace-label">管理工作台</span><nav aria-label="管理导航">${items.map(([key,url,label])=>`<a href="${url}" ${active===key?'aria-current="page"':''}>${navIcon(key)}<span class="nav-label">${label}</span></a>`).join('')}</nav>${accountControls(email)}</aside>`}<main class="${active==='login'?'login-main':'main'}">${content}</main>${active === 'login' ? '' : accountSettings(email)}<div id="toast" class="toast" role="status" hidden></div><dialog id="confirm-dialog" aria-labelledby="confirm-title"><div class="dialog-inner"><h2 id="confirm-title"></h2><p id="confirm-message"></p><div class="dialog-actions"><button class="button secondary" type="button" data-close>取消</button><button class="button" type="button" id="confirm-ok">确定</button></div></div></dialog><dialog id="key-dialog" aria-labelledby="key-title"><div class="dialog-inner"><h2 id="key-title">API Key</h2><p>仅显示一次，请立即保存。</p><textarea id="issued-key" readonly rows="3" spellcheck="false" aria-label="API Key"></textarea><div class="dialog-actions"><button class="button secondary" type="button" data-copy="issued-key">复制</button><button class="button" type="button" id="close-key">我已保存</button></div></div></dialog></body></html>`;
}
export const pageHead = (eyebrow: string, title: string, subtitle: string, action = '') => `<header class="page-head"><div>${eyebrow?`<p class="eyebrow">${esc(eyebrow)}</p>`:''}<h1>${esc(title)}</h1>${subtitle?`<p class="subtitle">${esc(subtitle)}</p>`:''}</div>${action}</header>`;
export function loginPage() {
  return layout('管理员登录','login','','',`<a class="brand" href="/">${brandMark} connany</a><div class="login-grid"><section class="login-story"><p class="eyebrow">一个连接服务，多个 Agent</p><h1>配好一次。<br>连接每个 agent。</h1><p>集中管理平台凭证，为不同 agent 分发独立密钥，让用户授权自己的工作空间。</p><div class="login-platforms"><span>Notion</span><span>GitHub</span><span>Linear</span></div><div class="mini-wire" aria-hidden="true">└────────── Connany ──────────┘</div></section><section class="panel login-panel"><p class="eyebrow">管理工作台</p><h2>管理员登录</h2><form data-api="/admin/api/login" data-redirect="/admin"><label>邮箱<input name="email" type="email" autocomplete="username" required autofocus placeholder="admin@example.com"></label><label>密码<input name="password" type="password" autocomplete="current-password" required maxlength="256"></label><p class="form-error" role="alert" hidden></p><button class="button full" type="submit">进入工作台 →</button></form><details class="setup-note"><summary>首次使用或忘记密码？</summary><p>在服务端运行以下命令创建管理员或重置密码：</p><code>npm run admin:create -- admin@example.com</code><p>密码至少 12 位。重置后其他登录会话会失效。</p></details></section></div>`);
}
export function overview(providers: ProviderView[], counts: any) {
  const ready = providers.filter(p=>p.enabled).length;
  return pageHead('服务总览','连接，从这里开始。','平台凭证集中配置；每个 agent 独立接入，每位用户单独授权。')+
    `<section class="shared-flow panel"><div class="flow-label"><span class="tiny">共享连接器</span><span class="tiny">独立 API Key</span></div><div class="flow-row"><div class="flow-platforms">${providers.map(p=>`<a href="${providerHref(p.name)}" class="flow-provider"><span class="provider-icon ${p.name}">${icons[p.name]}</span><span>${names[p.name]}</span><i class="dot ${p.enabled?'on':''}" aria-label="${p.enabled?'已启用':'未启用'}"></i></a>`).join('')}</div><div class="flow-line" aria-hidden="true"></div><div class="flow-hub">${brandMark}<span>Connany</span></div><div class="flow-line" aria-hidden="true"></div><a class="flow-agent" href="/admin/keys"><strong>${counts.projects}</strong><span>API Keys ↗</span></a></div><p class="flow-caption">一次配置，所有接入共用。不同 API Key 的接入空间与用户数据相互隔离。</p></section>
    <div class="stats"><div class="stat"><span>已启用平台</span><strong>${ready}<small> / 3</small></strong></div><div class="stat"><span>可用 API Keys</span><strong>${counts.active_projects}</strong></div><div class="stat"><span>已授权用户连接</span><strong>${counts.connections}</strong></div></div>
    <div class="section-title"><h2>开始接入</h2><span class="tiny">从配置到调用</span></div><div class="steps"><a class="panel step" href="/admin/connectors"><span class="step-number">01</span><h3>启用连接器</h3><p>启用官方 MCP，配置 GitHub App 和授权回调。</p><span class="step-link">${ready ? '管理连接器' : '启用第一个连接器'} ↗</span></a><a class="panel step" href="/admin/keys#new-key"><span class="step-number">02</span><h3>创建 API Key</h3><p>为每个产品生成独立 API key，并登记授权返回地址。</p><span class="step-link">创建 API Key ↗</span></a><a class="panel step" href="/admin/guide"><span class="step-number">03</span><h3>交给 Agent 接入</h3><p>提供服务地址、API Key和文档，完成一次真实账号授权。</p><span class="step-link">查看接入说明 ↗</span></a></div>`;
}
const providerStatus = (p: ProviderView) => badge(p.enabled?'已启用':p.configured?'已暂停':'未启用',p.enabled?'green':'');
export const providerHref = (name: ProviderView['name']) => `/admin/connectors#${providerSpec(name).auth === 'mcp' ? 'card' : 'provider'}-${name}`;
function githubCreationUrl(callbackUrl: string) {
  const url = new URL('https://github.com/settings/apps/new');
  url.search = new URLSearchParams({
    url: new URL(callbackUrl).origin,
    'callback_urls[]': callbackUrl,
    request_oauth_on_install: 'false',
    webhook_active: 'false',
  }).toString();
  return url.toString();
}
function credentialDialog(p: ProviderView) {
  const id = `provider-${p.name}`;
  return `<dialog id="${id}" aria-labelledby="${id}-title"><div class="dialog-inner"><h2 id="${id}-title">${names[p.name]}</h2><form data-api="/admin/api/providers/${p.name}" data-success="已保存" data-reload><label>Client ID<input name="client_id" value="${esc(p.client_id)}" required maxlength="300" autocomplete="off" spellcheck="false"></label><label>Client Secret<input name="client_secret" type="password" autocomplete="new-password" maxlength="2000" placeholder="${p.has_secret?'已保存，留空不变':''}"></label><div class="provider-app-links"><a href="${esc(githubCreationUrl(p.callback_url))}" target="_blank" rel="noopener noreferrer">创建 GitHub App ↗</a><a href="https://github.com/settings/apps" target="_blank" rel="noopener noreferrer">管理已有应用 ↗</a></div><label>App slug<input name="github_app_slug" value="${esc(p.github_app_slug)}" required maxlength="100" pattern="[a-zA-Z0-9-]+" placeholder="填写应用地址最后一段，例如 my-app" aria-describedby="${id}-slug-help" autocomplete="off" spellcheck="false"></label><div id="${id}-slug-help" class="help provider-slug-help">填写 GitHub App 公开地址的最后一段。例如地址为 github.com/apps/my-app，则填写 my-app。用于生成安装链接，不是 App ID。</div><label>回调地址<input id="${id}-callback" value="${esc(p.callback_url)}" readonly aria-describedby="${id}-callback-help"></label><div id="${id}-callback-help" class="help provider-slug-help">复制此地址到 GitHub App 设置中的 Callback URL，需保持完全一致。</div><input type="hidden" name="enabled" value="${p.enabled || !p.configured}"><p class="form-error" role="alert" hidden></p><div class="dialog-actions"><button type="button" class="button secondary" data-close>取消</button><button class="button" type="submit">保存</button></div></form></div></dialog>`;
}
function providerCard(p: ProviderView) {
  const label = names[p.name];
  const toggle = `<form data-api="/admin/api/providers/${p.name}" data-success="${label} 已${p.enabled?'暂停':'启用'}" data-reload><input type="hidden" name="enabled" value="${!p.enabled}"><button class="button ${p.enabled?'secondary':''} small" type="submit" ${p.configured || providerSpec(p.name).auth==='mcp'?'':'disabled'}>${p.enabled?'暂停':'启用'}</button></form>`;
  const configure = providerSpec(p.name).auth === 'mcp' ? '' : `<button class="button secondary small" type="button" data-dialog="provider-${p.name}">配置</button>`;
  return `<section class="panel provider-card" id="card-${p.name}"><div class="card-top"><span class="provider-icon large ${p.name}">${icons[p.name]}</span>${providerStatus(p)}</div><div class="provider-name"><h2>${label}</h2><span class="provider-tag">MCP</span></div><p>${esc(providerSpec(p.name).description)}</p><div class="card-actions">${configure}${toggle}<a class="provider-website" href="${esc(providerSpec(p.name).website)}" target="_blank" rel="noopener noreferrer" aria-label="访问 ${esc(label)} 官网（新标签页）">官网 ↗</a></div></section>`;
}
export function providerList(providers: ProviderView[]) {
  return pageHead('','连接器','')+`<div class="provider-grid">${providers.map(providerCard).join('')}</div>`+
    providers.filter(p=>providerSpec(p.name).auth!=='mcp').map(credentialDialog).join('');
}
const keyFields = (p?: any) => `<label>名称<input name="name" required maxlength="100" value="${esc(p?.name || '')}"></label><p class="form-error" role="alert" hidden></p>`;
const keyDialog = (id: string, title: string, form: string) => `<dialog id="${id}" aria-labelledby="${id}-title"><div class="dialog-inner"><h2 id="${id}-title" ${id.startsWith('edit-')?'translate="no"':''}>${esc(title)}</h2>${form}</div></dialog>`;
const dialogActions = (submit: string) => `<div class="dialog-actions"><button type="button" class="button secondary" data-close>取消</button><button class="button" type="submit">${submit}</button></div>`;
export function projectList(projects: any[], next: string | null) {
  const rows = projects.map(p=>`<tr id="key-${esc(p.id)}"><td><strong translate="no">${esc(p.name)}</strong></td><td>${badge(p.enabled?'已启用':'已停用',p.enabled?'green':'')}</td><td><code>${esc(p.key_prefix || '旧版密钥')}…</code></td><td>${p.connection_count}</td><td><div class="row-actions"><button class="button secondary small" type="button" data-dialog="edit-${esc(p.id)}">编辑</button><form data-api="/admin/api/projects/${esc(p.id)}/rotate-key" data-key-result data-confirm-title="轮换 ${esc(p.name)}？" data-confirm="旧 key 会立即失效，需同步更新 Agent 后端。" data-confirm-action="轮换"><button class="button secondary small" type="submit">轮换</button></form><form data-api="/admin/api/projects/${esc(p.id)}/status" data-reload data-success="${p.enabled?'已停用':'已启用'}"${p.enabled?` data-confirm-title="停用 ${esc(p.name)}？" data-confirm="停用后此 key 无法调用 Connany，用户连接保留。" data-confirm-action="停用"`:''}><input type="hidden" name="enabled" value="${!p.enabled}"><button class="button secondary small" type="submit">${p.enabled?'停用':'启用'}</button></form><form data-api="/admin/api/projects/${esc(p.id)}/delete" data-reload data-success="已删除" data-confirm-title="删除 ${esc(p.name)}？" data-confirm="key 立即失效，${p.connection_count} 个用户连接将被断开并删除，无法恢复。" data-confirm-action="删除" data-danger><button class="button secondary small danger" type="submit">删除</button></form></div></td></tr>`).join('');
  return pageHead('','API Keys','',`<button class="button" type="button" data-dialog="new-key">创建</button>`)+
    (projects.length?`<section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>名称</th><th>状态</th><th>Key</th><th>用户连接</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`:`<section class="panel empty"><p>暂无 API Key</p></section>`)+
    (next?`<a class="text-link" href="/admin/keys?after=${esc(next)}">下一页 →</a>`:'')+
    keyDialog('new-key','创建 API Key',`<form data-api="/admin/api/projects" data-key-result>${keyFields()}${dialogActions('创建')}</form>`)+
    projects.map(p=>keyDialog(`edit-${esc(p.id)}`,p.name,`<form data-api="/admin/api/projects/${esc(p.id)}" data-reload data-success="已保存">${keyFields(p)}${dialogActions('保存')}</form>`)).join('');
}
export function connectionsPage(rows: any[], project: string, provider: string, next: string | null) {
  const query = new URLSearchParams({ ...(project?{project_id:project}:{}), ...(provider?{provider}:{}), ...(next?{after:next}:{}) });
  return pageHead('授权管理','用户连接','查看各个 agent 用户授权的账号。断开连接会立即阻止 Connany 后续调用。')+
    `<form class="filters" method="get"><label>接入 ID<input name="project_id" value="${esc(project)}" placeholder="全部 API Keys"></label><label>平台<select name="provider"><option value="">全部平台</option>${Object.entries(names).map(([key,name])=>`<option value="${key}" ${key===provider?'selected':''}>${name}</option>`).join('')}</select></label><button class="button secondary" type="submit">筛选</button></form><section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>账号 / 工作区</th><th>API Key / 用户</th><th>平台</th><th>状态</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><strong translate="no">${esc(c.identity.account_name)}</strong><span class="sub-id" translate="no">${esc(c.identity.workspace_name || '')}</span></td><td translate="no">${esc(c.project_name)}<code class="sub-id">${esc(c.external_user_id)}</code></td><td>${names[c.provider]}</td><td>${badge(c.status==='connected'?'已连接':c.status==='reauth_required'?'需要重连':'已断开',c.status==='connected'?'green':'')}<small class="sub-id">${c.revocation_status==='failed'?'平台撤销失败，可重试':''}</small></td><td>${c.status!=='revoked' || c.revocation_status==='failed'?`<form data-api="/admin/api/connections/${c.id}/disconnect" data-reload data-confirm="确定断开此用户连接？这会撤销对应平台授权，共享的上游授权也可能受到影响。"><button class="text-button danger" type="submit">${c.status==='revoked'?'重试撤销':'断开连接'}</button></form>`:'—'}</td></tr>`).join('') || '<tr><td colspan="5" class="empty-cell">暂无用户连接。将API Key交给 agent，完成一次用户授权后会显示在这里。</td></tr>'}</tbody></table></div></section>${next?`<a class="text-link" href="/admin/connections?${esc(query.toString())}">下一页 →</a>`:''}`;
}
export function activityPage(events: any[], audits: any[]) {
  return pageHead('运行记录','操作记录','最近 100 条用户调用与管理员操作，不记录 token、凭证或业务正文。')+
    `<h2 class="section-title">用户连接与调用</h2><section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>时间（UTC+8）</th><th>API Key / 用户</th><th>事件</th><th>操作 / 错误</th></tr></thead><tbody>${events.map(e=>`<tr><td class="nowrap">${esc(new Date(e.created_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}))}</td><td translate="no">${esc(e.project_name)}<code class="sub-id">${esc(e.external_user_id)}</code></td><td><code>${esc(e.type)}</code></td><td><code>${esc(e.data?.action || e.data?.error_code || '—')}</code></td></tr>`).join('') || '<tr><td colspan="4" class="empty-cell">暂无用户调用记录</td></tr>'}</tbody></table></div></section><h2 class="section-title">管理员操作</h2><section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>时间（UTC+8）</th><th>管理员</th><th>操作</th><th>对象</th></tr></thead><tbody>${audits.map(e=>`<tr><td class="nowrap">${esc(new Date(e.created_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}))}</td><td>${esc(e.email)}</td><td><code>${esc(e.action)}</code></td><td><code>${esc(e.target)}</code></td></tr>`).join('') || '<tr><td colspan="4" class="empty-cell">暂无管理员操作</td></tr>'}</tbody></table></div></section>`;
}
export function guidePage(base: string, prompt: string) {
  return pageHead('开发者接入','把这些交给你的 Agent','同一套连接器可供多个 agent 使用。每把 API Key 只访问所属接入空间的用户连接。')+`<section class="panel guide"><h2>复制给开发 Agent</h2><p>把下面的提示交给负责开发的 agent，密钥通过后端环境变量另行配置。</p><textarea id="agent-prompt" readonly rows="16">${esc(prompt)}</textarea><button class="button small" type="button" data-copy="agent-prompt">复制完整接入提示</button><h2>服务地址</h2><input id="base-url" value="${esc(base)}" readonly><button type="button" class="button secondary small" data-copy="base-url">复制服务地址</button><h2>API Key</h2><p>在「API Keys」创建密钥，安全发送生成的 API key 给对应开发者。密钥只放在 agent 后端。</p><h2>最小接入流程</h2><ol><li>后端调用 <code>POST /v1/connect-sessions</code>，传入已认证用户的 external_user_id 和平台名称。</li><li>向该用户展示返回的 connect_url，让用户在浏览器中完成授权。</li><li>后端查询会话结果，获得 connection_id。</li><li>调用 <code>POST /v1/actions/execute</code> 读取已授权的数据。</li></ol><h2>完整接入文档</h2><a class="button secondary" href="/admin/guide/download">下载 Agent 接入文档</a> <a class="button secondary" href="/admin/guide/sdk">下载 TypeScript SDK</a><div class="callout">应用凭证共用不代表用户授权共用。用户须在各个 Agent 中授权自己的账号；上游平台共享应用的权限和撤销语义仍然适用。</div></section>`;
}

export function testPage(providers: ProviderView[], selected: string) {
  return pageHead('真实 API 联调','测试一个用户连接','使用API Key 验证授权与只读调用。建议创建测试专用 API Key，避免混入正式用户数据。') + `<div class="form-layout"><section class="panel"><form id="connection-test"><label>API Key<input id="test-key" type="password" autocomplete="off" required maxlength="200" placeholder="cn_live_…"><span class="help">仅在当前页面内存中使用，刷新后清空。此管理员测试工具直接调用 API；产品接入必须通过 agent 后端。</span></label><label>测试用户 ID<input id="test-user" required maxlength="200" value="connany-test-user"></label><label>测试平台<select id="test-provider">${providers.map(p=>`<option value="${p.name}" ${p.name===selected?'selected':''} ${p.enabled?'':'disabled'}>${names[p.name]}${p.enabled?'':'（未启用）'}</option>`).join('')}</select></label><button type="submit" class="button" ${providers.some(p=>p.enabled)?'':'disabled'}>1. 创建授权链接</button></form><p id="test-status" role="status" class="callout">等待创建测试会话。</p><div class="test-actions"><a id="test-open" class="button secondary" target="_blank" rel="noopener noreferrer" hidden>2. 打开授权页面 ↗</a><button id="test-check" class="button secondary" disabled>3. 检查授权结果</button><button id="test-read" class="button secondary" disabled>4. 试读数据</button></div><pre id="test-result" class="test-result" hidden></pre></section><aside class="form-aside"><section class="panel"><h3>如何完成测试</h3><ol><li>在「API Keys」创建密钥并安全保存。</li><li>生成链接，在新标签页完成自己的平台授权。</li><li>回到这里检查结果，再试读数据。</li></ol><p>Notion：读取官方 MCP 工具目录（不写入内容）；GitHub：列出所有可访问安装，由你选择组织试读仓库；Linear：读取官方 MCP 工具目录。空列表表示 API 调用成功，但没有可见数据。</p><p>GitHub 账号授权后，点击试读数据可查看组织、添加安装或管理仓库权限。修改后重新试读以刷新列表。测试结果仅展示在当前页面。</p><a href="/admin/keys#new-key">创建测试 API Key ↗</a></section><section class="panel"><h3>测试完成后</h3><p>连接会保留在「用户连接」中，可按测试用户 ID 识别并按需断开。断开可能撤销同一平台应用的共享授权。</p><a href="/admin/connections">查看用户连接 ↗</a><p><a href="/admin/guide">复制 Agent 接入提示 ↗</a></p></section></aside></div>`;
}
