import { brandMark, faviconLink } from '../brand.js';
import { maxActiveApiKeys } from '../projects.js';
import type { AdminIdentity, AdminRole } from './auth.js';
import type { ConnectorView } from '../connector-store.js';
import { categoryTitles, connector as connectorSpec, connectorCatalog, connectorCategories, connectorNames } from '../connectors/catalog.js';
export const esc = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' })[c]!);
export const names = Object.fromEntries(connectorNames.map(n => [n, connectorCatalog[n].label])) as Record<string,string>;
const icons = Object.fromEntries(connectorNames.map(n => [n, connectorCatalog[n].icon])) as Record<string,string>;
const badge = (text: string, tone = '') => `<span class="badge ${tone}">${esc(text)}</span>`;
const navIcon = (key: string) => {
  const paths: Record<string,string> = {
    overview:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
    connectors:'<path d="M8 3v4m8-4v4M6 7h12v4a6 6 0 0 1-12 0V7zm6 10v4"/>',
    projects:'<path d="M3 7.5A2.5 2.5 0 0 1 5.5 5H9l2 2.5h7.5A2.5 2.5 0 0 1 21 10v7.5a2.5 2.5 0 0 1-2.5 2.5h-13A2.5 2.5 0 0 1 3 17.5z"/>',
    test:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="m7 9 3 3-3 3m6 0h4"/>',
    guide:'<path d="M12 5v16M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2z"/>',
    connections:'<path d="m10 13 4-4m-5 7-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m2 0 2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',
    activity:'<path d="M8 3h12v18H4V3h4m0 5h8m-8 4h8m-8 4h5"/>',
    users:'<circle cx="9" cy="8" r="3.5"/><path d="M2.5 20a6.5 6.5 0 0 1 13 0M16 4.5a3.5 3.5 0 0 1 0 7m2.5 8.5a6.5 6.5 0 0 0-3-5.5"/>',
  };
  return `<svg class="nav-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[key] || paths.overview}</svg>`;
};
function accountControls(email: string) {
  const avatar = esc((email.split('@')[0] || 'AD').slice(0,2).toUpperCase());
  const icon = (path: string) => `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
  return `<div class="sidebar-bottom"><details class="account-menu"><summary aria-label="打开账号菜单"><span class="account-avatar" translate="no">${avatar}</span><span class="account-name" translate="no">${esc(email)}</span></summary><div class="account-popover"><div class="account-profile"><span class="account-avatar" translate="no">${avatar}</span><span class="account-name" translate="no">${esc(email)}</span></div><button type="button" class="account-action" data-dialog="account-settings">${icon('<path d="m9 3-1 3-3 1v4l-2 1 2 3 3 1 1 3h4l1-3 3-1 2-3-2-1V7l-3-1-1-3Z"/><circle cx="11" cy="11" r="3"/>')}设置</button><form data-api="/admin/api/logout" data-redirect="/admin/login"><button type="submit" class="account-action">${icon('<path d="M9 4H4v16h5m5-13 5 5-5 5M8 12h11"/>')}退出登录</button></form></div></details></div>`;
}
function accountSettings(email: string) {
  const icon = (path: string) => `<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${path}</svg>`;
  const icons = {account:icon('<circle cx="10" cy="8" r="3"/><path d="M4 20v-2a6 6 0 0 1 12 0v2m3-10v6m-3-3h6"/>'),general:icon('<circle cx="12" cy="12" r="9"/><circle cx="8" cy="10" r=".5"/><circle cx="12" cy="7" r=".5"/><circle cx="16" cy="10" r=".5"/><path d="M12 21v-5h5"/>'),about:icon('<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v.1"/>')};
  const themes = [ ['light','浅色',icon('<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>')], ['dark','深色',icon('<path d="M20 14A9 9 0 0 1 10 4a9 9 0 1 0 10 10Z"/>')], ['system','跟随系统',icon('<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M12 17v4m-4 0h8"/>')] ];
  return `<dialog id="account-settings" aria-label="设置"><div class="settings-layout"><aside class="settings-nav"><p>用户</p><div role="tablist" aria-label="设置分类" aria-orientation="vertical">${(['account','general','about'] as const).map((key,i)=>`<button type="button" role="tab" id="settings-tab-${key}" aria-controls="settings-${key}" aria-selected="${key==='general'}" tabindex="${key==='general'?0:-1}" data-settings-tab="${key}">${icons[key]}${['账户','通用','关于'][i]}</button>`).join('')}</div></aside><div class="settings-content"><button type="button" class="settings-close" data-close aria-label="关闭设置">×</button><section id="settings-account" role="tabpanel" aria-labelledby="settings-tab-account" hidden><h2>账户</h2><p class="settings-subtitle">管理你的管理员账号和登录密码。</p><div class="settings-account"><span class="tiny">管理员账号</span><strong translate="no">${esc(email)}</strong></div><h3>修改密码</h3><p>保存后会退出所有登录会话，请使用新密码重新登录。</p><form data-api="/admin/api/account/password" data-redirect="/admin/login"><label>当前密码<input type="password" name="current_password" autocomplete="current-password" required maxlength="256"></label><label>新密码<input type="password" name="new_password" autocomplete="new-password" required minlength="8" maxlength="256"><span class="help">8–256 个字符。</span></label><label>确认新密码<input type="password" name="confirm_password" autocomplete="new-password" required minlength="8" maxlength="256"></label><p class="form-error" role="alert" hidden></p><div class="dialog-actions"><button type="button" class="button secondary" data-close>取消</button><button type="submit" class="button">保存密码</button></div></form></section><section id="settings-general" role="tabpanel" aria-labelledby="settings-tab-general"><h2>通用</h2><p class="settings-subtitle">外观与当前设备偏好设置。</p><div class="settings-card"><h3>主题</h3><p>选择控制台配色。跟随系统会使用操作系统设置。</p><div class="theme-options" role="group" aria-label="主题">${themes.map(([value,label,glyph])=>`<button type="button" data-theme-choice="${value}" aria-pressed="false">${glyph}<span>${label}</span></button>`).join('')}</div></div><div class="settings-card"><h3>界面语言</h3><p>选择控制台使用的界面语言。</p><div class="language-options" role="group" aria-label="界面语言"><button type="button" data-language-choice="en" aria-pressed="true" translate="no">English</button><button type="button" data-language-choice="zh-CN" aria-pressed="false" translate="no">简体中文</button></div></div></section><section id="settings-about" role="tabpanel" aria-labelledby="settings-tab-about" hidden><h2>关于</h2><p class="settings-subtitle">Connany · Agent 连接器服务</p><div class="settings-card">${brandMark}<h3>连接工具与用户数据</h3><p>统一管理账号授权、连接与凭证，让 Agent 在用户授权范围内使用工具。</p><a href="/admin/docs/agent">Agent 接入指南 ↗</a></div></section></div></div></dialog>`;
}
export function layout(title: string, active: string, email: string, csrf: string, content: string, role: AdminRole = 'member') {
  const workbench = [['overview','/admin','总览'],['connectors','/admin/connectors','连接器'],['projects','/admin/projects','项目'],['connections','/admin/connections','用户连接'],['guide','/admin/docs','文档']];
  const system = role === 'admin' ? [['users','/admin/users','用户管理']] : [];
  const navGroup = (label: string, items: string[][]) => items.length ? `<span class="workspace-label">${label}</span><nav aria-label="${label}">${items.map(([key,url,text])=>`<a href="${url}" ${active===key?'aria-current="page"':''}>${navIcon(key)}<span class="nav-label">${text}</span></a>`).join('')}</nav>` : '';
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="csrf-token" content="${esc(csrf)}"><title>${esc(title)} · Connany</title>${faviconLink}<script src="/admin/assets/admin-preferences.js"></script><link rel="stylesheet" href="/admin/assets/admin.css"><script src="/admin/assets/admin-i18n.js" defer></script><script src="/admin/assets/admin.js" defer></script></head><body class="${active === 'login' ? 'login-body' : ''}">${active === 'login' ? '' : `<aside class="sidebar"><a href="/admin" class="brand">${brandMark} connany</a>${navGroup('工作台',workbench)}${navGroup('系统',system)}${accountControls(email)}</aside>`}<main class="${active==='login'?'login-main':'main'}">${content}</main>${active === 'login' ? '' : accountSettings(email)}<div id="toast" class="toast" role="status" hidden></div><dialog id="confirm-dialog" aria-labelledby="confirm-title"><div class="dialog-inner"><h2 id="confirm-title"></h2><p id="confirm-message"></p><div class="dialog-actions"><button class="button secondary" type="button" data-close>取消</button><button class="button" type="button" id="confirm-ok">确定</button></div></div></dialog><dialog id="key-dialog" aria-labelledby="key-title"><div class="dialog-inner"><h2 id="key-title">API Key</h2><p>仅显示一次，请立即保存。</p><textarea id="issued-key" readonly rows="3" spellcheck="false" aria-label="API Key"></textarea><div class="dialog-actions"><button class="button secondary" type="button" data-copy="issued-key">复制</button><button class="button" type="button" id="close-key">我已保存</button></div></div></dialog></body></html>`;
}
export const pageHead = (eyebrow: string, title: string, subtitle: string, action = '') => `<header class="page-head"><div>${eyebrow?`<p class="eyebrow">${esc(eyebrow)}</p>`:''}<h1>${esc(title)}</h1>${subtitle?`<p class="subtitle">${esc(subtitle)}</p>`:''}</div>${action}</header>`;
export function loginPage() {
  return layout('登录','login','','',`<a class="brand" href="/">${brandMark} connany</a><div class="login-grid"><section class="login-story"><p class="eyebrow">一个连接服务，多个 Agent</p><h1>配好一次。<br>连接每个 agent。</h1><p>集中管理连接器凭证，为每个项目分发独立密钥，让用户授权自己的账号。</p></section><section class="panel login-panel"><p class="eyebrow">管理工作台</p><h2>登录</h2><form data-api="/admin/api/login" data-redirect="/admin"><label>邮箱<input name="email" type="email" autocomplete="username" required autofocus placeholder="admin@example.com"></label><label>密码<input name="password" type="password" autocomplete="current-password" required maxlength="256"></label><p class="form-error" role="alert" hidden></p><button class="button full" type="submit">进入工作台 →</button></form></section></div>`);
}
export function overview(connectors: ConnectorView[], counts: any) {
  const enabled = connectors.filter(p=>p.enabled); const ready = enabled.length;
  // The overview shows a few connectors; the full list lives on the connectors page.
  const flowConnectors = enabled.length ? enabled.slice(0,4) : connectors.slice(0,3);
  return pageHead('服务总览','连接，从这里开始。','连接器凭证集中配置；每个项目独立接入，每位用户单独授权。')+
    `<section class="shared-flow panel"><div class="flow-label"><span class="tiny">共享连接器</span><span class="tiny">多个项目</span></div><div class="flow-row"><div class="flow-platforms">${flowConnectors.map(p=>`<a href="${connectorHref(p.name)}" class="flow-connector"><span class="connector-icon ${p.name}">${icons[p.name]}</span><span>${names[p.name]}</span><i class="dot ${p.enabled?'on':''}" aria-label="${p.enabled?'已启用':'未启用'}"></i></a>`).join('')}<a href="/admin/connectors" class="flow-connector flow-more">${enabled.length>flowConnectors.length?`+${enabled.length-flowConnectors.length} 个已启用`:`全部 ${connectors.length} 个连接器`} ↗</a></div><div class="flow-line" aria-hidden="true"></div><div class="flow-hub">${brandMark}<span>Connany</span></div><div class="flow-line" aria-hidden="true"></div><a class="flow-agent" href="/admin/projects"><strong>${counts.projects}</strong><span>项目 ↗</span></a></div><p class="flow-caption">连接器配置一次，所有项目共用；不同项目的用户与连接相互隔离。</p></section>
    <div class="stats"><div class="stat"><span>已启用连接器</span><strong>${ready}<small> / ${connectors.length}</small></strong></div><div class="stat"><span>已启用项目</span><strong>${counts.active_projects}</strong></div><div class="stat"><span>已授权用户连接</span><strong>${counts.connections}</strong></div></div>
    <div class="section-title"><h2>开始接入</h2><span class="tiny">从配置到调用</span></div><div class="steps"><a class="panel step" href="/admin/connectors"><span class="step-number">01</span><h3>启用连接器</h3><p>启用官方 MCP，配置 GitHub App 和授权回调。</p><span class="step-link">${ready ? '管理连接器' : '启用第一个连接器'} ↗</span></a><a class="panel step" href="/admin/projects#new-project"><span class="step-number">02</span><h3>创建项目</h3><p>为每个 agent 产品创建项目，获取它的 API Key。</p><span class="step-link">创建项目 ↗</span></a><a class="panel step" href="/admin/docs/agent"><span class="step-number">03</span><h3>交给 Agent 接入</h3><p>提供服务地址、项目的 API Key 和文档，完成一次真实账号授权。</p><span class="step-link">查看接入说明 ↗</span></a></div>`;
}
const connectorStatus = (p: ConnectorView) => badge(p.enabled?'已启用':p.configured?'已暂停':'未启用',p.enabled?'green':'');
export const connectorHref = (name: ConnectorView['name']) => `/admin/connectors#${connectorSpec(name).auth === 'mcp' ? 'card' : 'connector'}-${name}`;
function githubCreationUrl(callbackUrl: string) {
  const url = new URL('https://github.com/settings/apps/new');
  url.search = new URLSearchParams({
    url: new URL(callbackUrl).origin,
    'callback_urls[]': callbackUrl,
    request_oauth_on_install: 'false',
    webhook_active: 'false',
  }).toString();
  return url.toString();
}
function credentialDialog(p: ConnectorView) {
  const id = `connector-${p.name}`;
  return `<dialog id="${id}" aria-labelledby="${id}-title"><div class="dialog-inner"><h2 id="${id}-title">${names[p.name]}</h2><form data-api="/admin/api/connectors/${p.name}" data-success="已保存" data-reload><label>Client ID<input name="client_id" value="${esc(p.client_id)}" required maxlength="300" autocomplete="off" spellcheck="false"></label><label>Client Secret<input name="client_secret" type="password" autocomplete="new-password" maxlength="2000" placeholder="${p.has_secret?'已保存，留空不变':''}"></label><div class="connector-app-links"><a href="${esc(githubCreationUrl(p.callback_url))}" target="_blank" rel="noopener noreferrer">创建 GitHub App ↗</a><a href="https://github.com/settings/apps" target="_blank" rel="noopener noreferrer">管理已有应用 ↗</a></div><label>App slug<input name="github_app_slug" value="${esc(p.github_app_slug)}" required maxlength="100" pattern="[a-zA-Z0-9-]+" placeholder="填写应用地址最后一段，例如 my-app" aria-describedby="${id}-slug-help" autocomplete="off" spellcheck="false"></label><div id="${id}-slug-help" class="help connector-slug-help">填写 GitHub App 公开地址的最后一段。例如地址为 github.com/apps/my-app，则填写 my-app。用于生成安装链接，不是 App ID。</div><label>回调地址<input id="${id}-callback" value="${esc(p.callback_url)}" readonly aria-describedby="${id}-callback-help"></label><div id="${id}-callback-help" class="help connector-slug-help">复制此地址到 GitHub App 设置中的 Callback URL，需保持完全一致。</div><input type="hidden" name="enabled" value="${p.enabled || !p.configured}"><p class="form-error" role="alert" hidden></p><div class="dialog-actions"><button type="button" class="button secondary" data-close>取消</button><button class="button" type="submit">保存</button></div></form></div></dialog>`;
}
function connectorCard(p: ConnectorView) {
  const label = names[p.name];
  const toggle = `<form data-api="/admin/api/connectors/${p.name}" data-success="${label} 已${p.enabled?'暂停':'启用'}" data-reload><input type="hidden" name="enabled" value="${!p.enabled}"><button class="button ${p.enabled?'secondary':''} small" type="submit" ${p.configured || connectorSpec(p.name).auth==='mcp'?'':'disabled'}>${p.enabled?'暂停':'启用'}</button></form>`;
  const configure = connectorSpec(p.name).auth === 'mcp' ? '' : `<button class="button secondary small" type="button" data-dialog="connector-${p.name}">配置</button>`;
  const sync = `<form data-api="/admin/api/connectors/${p.name}/tool-sync" data-confirm-title="同步 ${esc(label)} 工具目录？" data-confirm="将跳转到 ${esc(label)} 授权页，用你的账号读取官方工具列表。本次授权只用于读取工具目录，完成后凭证会立即撤销，不会创建用户连接。" data-confirm-action="去授权"><button class="text-button" type="submit" ${p.enabled?'':'disabled'}>${p.tools_synced_at?'重新同步':'同步工具目录'}</button></form>`;
  const synced = p.tools_synced_at ? new Date(p.tools_synced_at) : null;
  const when = (options: Intl.DateTimeFormatOptions) => synced!.toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',...options});
  const status = synced ? `<strong>${p.tool_count} 个工具</strong><span title="${esc(when({}))}">${esc(when({month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}))} 同步</span>` : `<span>${p.enabled?'尚未同步':'启用后可同步'}</span>`;
  const catalog = `<div class="connector-tools"><div class="connector-tools-head"><span>工具目录</span>${p.enabled?sync:''}</div><div class="connector-tools-status">${status}</div></div>`;
  return `<section class="panel connector-card" id="card-${p.name}" data-connector="${p.name}" data-category="${connectorSpec(p.name).category}" data-enabled="${p.enabled}" data-search="${esc(`${label} ${p.name}`.toLowerCase())}"><div class="card-top"><span class="connector-icon large ${p.name}">${icons[p.name]}</span>${connectorStatus(p)}</div><div class="connector-name"><h2>${label}</h2><span class="connector-tag">MCP</span></div><p>${esc(connectorSpec(p.name).description['zh-CN'])}</p>${catalog}<div class="card-actions">${configure}${toggle}<a class="connector-website" href="${esc(connectorSpec(p.name).website)}" target="_blank" rel="noopener noreferrer" aria-label="访问 ${esc(label)} 官网（新标签页）">官网 ↗</a></div></section>`;
}
export function connectorList(connectors: ConnectorView[]) {
  const enabled = connectors.filter(p=>p.enabled).length;
  const filter = (kind: 'status'|'category', value: string, label: string, count: number) => `<button type="button" data-connector-${kind}="${value}" aria-pressed="${value==='all'}">${label}<span>${count}</span></button>`;
  const groups = connectorCategories.map(category => ({ category, items: connectors.filter(p=>connectorSpec(p.name).category===category) })).filter(group => group.items.length);
  return pageHead('','连接器','连接器配置一次，工作空间里的所有项目共用。')+
    `<div class="connector-toolbar"><div class="segmented" role="group" aria-label="启用状态">${filter('status','all','全部',connectors.length)}${filter('status','enabled','已启用',enabled)}${filter('status','disabled','未启用',connectors.length-enabled)}</div><input type="search" class="connector-search" data-connector-search placeholder="搜索连接器" aria-label="搜索连接器"></div>`+
    `<div class="connector-filters" role="group" aria-label="连接器分类">${filter('category','all','全部分类',connectors.length)}${groups.map(g=>filter('category',g.category,categoryTitles[g.category]['zh-CN'],g.items.length)).join('')}</div>`+
    groups.map(g=>`<section class="connector-group" data-group="${g.category}"><div class="section-title"><h2>${categoryTitles[g.category]['zh-CN']}</h2><span class="tiny" data-group-count>${g.items.length} 个</span></div><div class="connector-grid">${g.items.map(connectorCard).join('')}</div></section>`).join('')+
    `<section class="panel empty" data-connector-empty hidden><p>没有匹配的连接器</p></section>`+
    connectors.filter(p=>connectorSpec(p.name).auth!=='mcp').map(credentialDialog).join('');
}
const nameField = (label: string, value = '', required = true) => `<label>${label}<input name="name" ${required?'required':''} maxlength="100" value="${esc(value)}"></label><p class="form-error" role="alert" hidden></p>`;
const formDialog = (id: string, title: string, form: string) => `<dialog id="${id}" aria-labelledby="${id}-title"><div class="dialog-inner"><h2 id="${id}-title" ${id.startsWith('edit-')?'translate="no"':''}>${esc(title)}</h2>${form}</div></dialog>`;
const dialogActions = (submit: string) => `<div class="dialog-actions"><button type="button" class="button secondary" data-close>取消</button><button class="button" type="submit">${submit}</button></div>`;
const time = (value: unknown) => value ? esc(new Date(value as string).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})) : '—';
export function projectList(projects: any[], next: string | null) {
  const rows = projects.map(p=>`<tr id="project-${esc(p.id)}"><td><a class="table-title" href="/admin/projects/${esc(p.id)}" translate="no">${esc(p.name)}</a><code class="sub-id">${esc(p.id)}</code></td><td>${badge(p.enabled?'已启用':'已停用',p.enabled?'green':'')}</td><td>${p.api_key_count}</td><td>${p.connection_count}</td><td><a class="button secondary small" href="/admin/projects/${esc(p.id)}">管理</a></td></tr>`).join('');
  return pageHead('','项目','每个项目对应一个接入 Connany 的 agent 产品，拥有独立的 API Key 和用户连接。',`<button class="button" type="button" data-dialog="new-project">创建项目</button>`)+
    (projects.length?`<section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>项目</th><th>状态</th><th>API Keys</th><th>用户连接</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`:`<section class="panel empty"><p>暂无项目</p></section>`)+
    (next?`<a class="text-link" href="/admin/projects?after=${esc(next)}">下一页 →</a>`:'')+
    formDialog('new-project','创建项目',`<form data-api="/admin/api/projects" data-key-result>${nameField('名称')}<p class="help">创建后会生成第一个 API Key，仅显示一次。</p>${dialogActions('创建')}</form>`);
}
export function projectDetail(project: any, keys: any[]) {
  const active = keys.filter(k=>!k.revoked_at).length;
  const keyRows = keys.map(k=>`<tr><td>${k.name?`<strong translate="no">${esc(k.name)}</strong>`:'<span class="sub-id">未命名</span>'}<code class="sub-id">${esc(k.key_prefix)}…</code></td><td>${badge(k.revoked_at?'已吊销':'有效',k.revoked_at?'':'green')}</td><td class="nowrap">${time(k.created_at)}</td><td class="nowrap">${time(k.last_used_at)}</td><td>${k.revoked_at?'—':`<form data-api="/admin/api/api-keys/${esc(k.id)}/revoke" data-reload data-success="已吊销" data-confirm-title="吊销此 API Key？" data-confirm="${active<=1?'这是最后一个有效 API Key，吊销后此项目将无法调用 Connany。':'使用此 Key 的请求会立即失败，请确认 agent 已切换到新 Key。'}" data-confirm-action="吊销" data-danger><button class="button secondary small danger" type="submit">吊销</button></form>`}</td></tr>`).join('');
  return pageHead('项目',project.name,'',`<div class="row-actions"><button class="button secondary" type="button" data-dialog="edit-project">重命名</button><form data-api="/admin/api/projects/${esc(project.id)}/status" data-reload data-success="${project.enabled?'已停用':'已启用'}"${project.enabled?` data-confirm-title="停用 ${esc(project.name)}？" data-confirm="停用后此项目的所有 API Key 都无法调用 Connany，用户连接保留。" data-confirm-action="停用"`:''}><input type="hidden" name="enabled" value="${!project.enabled}"><button class="button secondary" type="submit">${project.enabled?'停用':'启用'}</button></form></div>`)+
    `<div class="stats"><div class="stat"><span>Project ID</span><code translate="no">${esc(project.id)}</code></div><div class="stat"><span>状态</span><strong>${badge(project.enabled?'已启用':'已停用',project.enabled?'green':'')}</strong></div><div class="stat"><span>用户连接</span><strong>${project.connection_count}</strong><a class="text-link" href="/admin/connections?project_id=${encodeURIComponent(project.id)}">查看 ↗</a></div></div>
    <div class="section-title"><h2>API Keys</h2>${active<maxActiveApiKeys?`<button class="button small" type="button" data-dialog="new-api-key">新建 API Key</button>`:`<span class="tiny">最多 ${maxActiveApiKeys} 个有效 Key，吊销旧 Key 后可新建</span>`}</div>
    <section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>名称 / 前缀</th><th>状态</th><th>创建时间（UTC+8）</th><th>最后使用（UTC+8）</th><th></th></tr></thead><tbody>${keyRows || '<tr><td colspan="5" class="empty-cell">暂无 API Key</td></tr>'}</tbody></table></div></section>
    <p class="help">轮换方式：新建 API Key，部署到 agent 后端后，再吊销旧 Key，期间两把 Key 同时有效。</p>
    <div class="section-title"><h2>危险操作</h2></div><section class="panel"><p>删除项目会吊销所有 API Key，断开并删除 ${project.connection_count} 个用户连接，无法恢复。</p><form data-api="/admin/api/projects/${esc(project.id)}/delete" data-redirect="/admin/projects" data-confirm-title="删除 ${esc(project.name)}？" data-confirm="所有 API Key 立即失效，${project.connection_count} 个用户连接将被断开并删除，无法恢复。" data-confirm-action="删除" data-danger><button class="button secondary small danger" type="submit">删除项目</button></form></section>`+
    formDialog('edit-project',project.name,`<form data-api="/admin/api/projects/${esc(project.id)}" data-reload data-success="已保存">${nameField('名称',project.name)}${dialogActions('保存')}</form>`)+
    formDialog('new-api-key','新建 API Key',`<form data-api="/admin/api/projects/${esc(project.id)}/api-keys" data-key-result>${nameField('备注名（可选）','',false)}<p class="help">例如 production、staging，便于区分。</p>${dialogActions('创建')}</form>`);
}
export function connectionsPage(rows: any[], projects: { id: string; name: string }[], project: string, connector: string, next: string | null) {
  const query = new URLSearchParams({ ...(project?{project_id:project}:{}), ...(connector?{connector}:{}), ...(next?{after:next}:{}) });
  return pageHead('','用户连接','查看各个项目下用户授权的账号。断开连接会立即阻止 Connany 后续调用。')+
    `<form class="filters" method="get" data-auto-submit><span class="select"><select name="project_id" aria-label="项目"><option value="">全部项目</option>${projects.map(p=>`<option value="${esc(p.id)}" ${p.id===project?'selected':''} translate="no">${esc(p.name)}</option>`).join('')}</select></span><span class="select"><select name="connector" aria-label="连接器"><option value="">全部连接器</option>${Object.entries(names).map(([key,name])=>`<option value="${key}" ${key===connector?'selected':''}>${name}</option>`).join('')}</select></span><noscript><button class="button secondary" type="submit">筛选</button></noscript></form><section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>账号 / 工作区</th><th>项目 / 用户</th><th>连接器</th><th>状态</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><strong translate="no">${esc(c.identity.account_name)}</strong><span class="sub-id" translate="no">${esc(c.identity.workspace_name || '')}</span></td><td translate="no">${esc(c.project_name)}<code class="sub-id">${esc(c.external_user_id)}</code></td><td>${names[c.connector]}</td><td>${badge(c.status==='connected'?'已连接':c.status==='reauth_required'?'需要重连':'已断开',c.status==='connected'?'green':'')}<small class="sub-id">${c.revocation_status==='failed'?'平台撤销失败，可重试':''}</small></td><td>${c.status!=='revoked' || c.revocation_status==='failed'?`<form data-api="/admin/api/connections/${c.id}/disconnect" data-reload data-confirm="确定断开此用户连接？这会撤销对应平台授权，共享的上游授权也可能受到影响。"><button class="text-button danger" type="submit">${c.status==='revoked'?'重试撤销':'断开连接'}</button></form>`:'—'}</td></tr>`).join('') || '<tr><td colspan="5" class="empty-cell">暂无用户连接。把项目的 API Key 交给 agent，完成一次用户授权后会显示在这里。</td></tr>'}</tbody></table></div></section>${next?`<a class="text-link" href="/admin/connections?${esc(query.toString())}">下一页 →</a>`:''}`;
}
export function activityPage(events: any[], audits: any[]) {
  return pageHead('运行记录','操作记录','最近 100 条用户调用与管理员操作，不记录 token、凭证或业务正文。')+
    `<h2 class="section-title">用户连接与调用</h2><section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>时间（UTC+8）</th><th>项目 / 用户</th><th>事件</th><th>操作 / 错误</th></tr></thead><tbody>${events.map(e=>`<tr><td class="nowrap">${esc(new Date(e.created_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}))}</td><td translate="no">${esc(e.project_name)}<code class="sub-id">${esc(e.external_user_id)}</code></td><td><code>${esc(e.type)}</code></td><td><code>${esc(e.data?.tool || e.data?.action || e.data?.error_code || '—')}</code></td></tr>`).join('') || '<tr><td colspan="4" class="empty-cell">暂无用户调用记录</td></tr>'}</tbody></table></div></section><h2 class="section-title">管理员操作</h2><section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>时间（UTC+8）</th><th>管理员</th><th>操作</th><th>对象</th></tr></thead><tbody>${audits.map(e=>`<tr><td class="nowrap">${esc(new Date(e.created_at).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}))}</td><td>${esc(e.email)}</td><td><code>${esc(e.action)}</code></td><td><code>${esc(e.target)}</code></td></tr>`).join('') || '<tr><td colspan="4" class="empty-cell">暂无管理员操作</td></tr>'}</tbody></table></div></section>`;
}
type RenderedDoc = { nav: { id: string; title: string }[]; html: string };
const docsTabs = (active: 'api' | 'agent', actions: string) => `<div class="docs-tabs"><nav aria-label="文档类型"><a href="/admin/docs" ${active==='api'?'aria-current="page"':''}>API 文档</a><a href="/admin/docs/agent" ${active==='agent'?'aria-current="page"':''}>Agent 接入指南</a></nav><div class="docs-actions">${actions}</div></div>`;
const docsBody = (doc: RenderedDoc, label: string) => `<div class="admin-docs-layout"><nav aria-label="${label}">${doc.nav.map(n=>`<a href="#${n.id}">${esc(n.title)}</a>`).join('')}</nav><div class="admin-docs-body">${doc.html}</div></div>`;
export function docsPage(docs: (RenderedDoc & { language: string })[]) {
  const markdown = docs.map(d=>`<a class="button secondary small" data-docs-lang="${d.language}" href="/docs/api.md?lang=${d.language}" download>下载 Markdown</a>`).join('');
  return pageHead('','文档','')+docsTabs('api',`${markdown}<a class="button secondary small" href="/docs/sdk.ts" download>TypeScript SDK</a>`)+
    docs.map(d=>`<div class="admin-docs" data-docs-lang="${d.language}" translate="no">${docsBody(d,d.language==='zh-CN'?'文档目录':'Documentation sections')}</div>`).join('');
}
export function agentDocsPage(doc: RenderedDoc, prompt: string) {
  return pageHead('','文档','')+docsTabs('agent',`<button class="button small" type="button" data-copy="agent-prompt">复制给开发 Agent</button><a class="button secondary small" href="/admin/guide/download" download>下载 Markdown</a><a class="button secondary small" href="/admin/guide/sdk" download>TypeScript SDK</a>`)+
    `<p class="docs-hint">把「复制给开发 Agent」的内容交给负责开发的 agent，它包含服务地址、实现要求和下面的完整指南。API Key 请通过后端环境变量另行配置。</p><textarea id="agent-prompt" class="visually-hidden" readonly tabindex="-1" aria-hidden="true">${esc(prompt)}</textarea>`+
    `<div class="admin-docs" translate="no">${docsBody(doc,'文档目录')}</div>`;
}

const roleLabels: Record<AdminRole, string> = { admin: '系统管理员', member: '普通用户' };
const roleOptions = (selected: AdminRole) => (Object.keys(roleLabels) as AdminRole[]).map(role=>`<option value="${role}" ${role===selected?'selected':''}>${roleLabels[role]}</option>`).join('');
export function usersPage(users: { id: string; email: string; role: AdminRole; created_at: Date; last_login_at: Date | null }[], me: AdminIdentity) {
  const rows = users.map(u => {
    const self = u.id === me.id;
    const role = self ? badge(roleLabels[u.role], u.role==='admin'?'green':'') : `<form data-api="/admin/api/users/${esc(u.id)}/role" data-auto-submit data-reload data-success="身份已更新"><span class="select"><select name="role" aria-label="身份">${roleOptions(u.role)}</select></span></form>`;
    const actions = `<div class="row-actions"><button class="button secondary small" type="button" data-dialog="${self?'account-settings':`password-${esc(u.id)}`}">${self?'修改密码':'重置密码'}</button>${self?'':`<form data-api="/admin/api/users/${esc(u.id)}/delete" data-reload data-success="已删除" data-confirm-title="删除用户 ${esc(u.email)}？" data-confirm="将同时删除该用户工作空间中的所有数据：项目、API Key、连接器配置和用户连接（会尝试撤销平台授权），无法恢复。操作记录会保留。" data-confirm-action="删除" data-danger><button class="button secondary small danger" type="submit">删除</button></form>`}</div>`;
    return `<tr><td><strong translate="no">${esc(u.email)}</strong>${self?'<span class="sub-id">当前账号</span>':''}</td><td>${role}</td><td class="nowrap">${time(u.created_at)}</td><td class="nowrap">${time(u.last_login_at)}</td><td>${actions}</td></tr>`;
  }).join('');
  const passwordDialog = (u: { id: string; email: string }) => u.id === me.id ? '' : formDialog(`password-${esc(u.id)}`,`重置 ${u.email} 的密码`,`<form data-api="/admin/api/users/${esc(u.id)}/password" data-reload data-success="密码已重置"><label>新密码<input type="password" name="password" autocomplete="new-password" required minlength="8" maxlength="256"><span class="help">8–256 个字符。保存后该用户的所有登录会话都会失效，需要用新密码重新登录。</span></label><p class="form-error" role="alert" hidden></p>${dialogActions('重置密码')}</form>`);
  return pageHead('','用户管理','系统管理员可以管理所有用户；普通用户可以使用工作台，看不到系统设置。',`<button class="button" type="button" data-dialog="new-user">添加用户</button>`)+
    `<section class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>邮箱</th><th>身份</th><th>创建时间（UTC+8）</th><th>最近登录（UTC+8）</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`+
    formDialog('new-user','添加用户',`<form data-api="/admin/api/users" data-reload data-success="用户已添加"><label>邮箱<input type="email" name="email" required maxlength="254" autocomplete="off"></label><label>初始密码<input type="password" name="password" autocomplete="new-password" required minlength="8" maxlength="256"><span class="help">8–256 个字符。请通过安全渠道告知对方，对方可登录后在「设置 → 账户」中修改。</span></label><label>身份<span class="select"><select name="role">${roleOptions('member')}</select></span></label><p class="form-error" role="alert" hidden></p>${dialogActions('添加')}</form>`)+
    users.map(passwordDialog).join('');
}

export function testPage(connectors: ConnectorView[], selected: string) {
  return pageHead('真实 API 联调','测试一个用户连接','使用项目的 API Key 验证授权与只读调用。建议创建测试专用项目，避免混入正式用户数据。') + `<div class="form-layout"><section class="panel"><form id="connection-test"><label>API Key<input id="test-key" type="password" autocomplete="off" required maxlength="200" placeholder="cn_live_…"><span class="help">仅在当前页面内存中使用，刷新后清空。此管理员测试工具直接调用 API；产品接入必须通过 agent 后端。</span></label><label>测试用户 ID<input id="test-user" required maxlength="200" value="connany-test-user"></label><label>测试连接器<select id="test-connector">${connectors.map(p=>`<option value="${p.name}" ${p.name===selected?'selected':''} ${p.enabled?'':'disabled'}>${names[p.name]}${p.enabled?'':'（未启用）'}</option>`).join('')}</select></label><button type="submit" class="button" ${connectors.some(p=>p.enabled)?'':'disabled'}>1. 创建授权链接</button></form><p id="test-status" role="status" class="callout">等待创建测试会话。</p><div class="test-actions"><a id="test-open" class="button secondary" target="_blank" rel="noopener noreferrer" hidden>2. 打开授权页面 ↗</a><button id="test-check" class="button secondary" disabled>3. 检查授权结果</button><button id="test-read" class="button secondary" disabled>4. 试读数据</button></div><pre id="test-result" class="test-result" hidden></pre></section><aside class="form-aside"><section class="panel"><h3>如何完成测试</h3><ol><li>在「项目」中创建测试项目并保存 API Key。</li><li>生成链接，在新标签页完成自己的平台授权。</li><li>回到这里检查结果，再试读数据。</li></ol><p>Notion：读取官方 MCP 工具目录（不写入内容）；GitHub：列出所有可访问安装，由你选择组织试读仓库；Linear：读取官方 MCP 工具目录。空列表表示 API 调用成功，但没有可见数据。</p><p>GitHub 账号授权后，点击试读数据可查看组织、添加安装或管理仓库权限。修改后重新试读以刷新列表。测试结果仅展示在当前页面。</p><a href="/admin/projects#new-project">创建测试项目 ↗</a></section><section class="panel"><h3>测试完成后</h3><p>连接会保留在「用户连接」中，可按测试用户 ID 识别并按需断开。断开可能撤销同一平台应用的共享授权。</p><a href="/admin/connections">查看用户连接 ↗</a><p><a href="/admin/docs/agent">复制 Agent 接入提示 ↗</a></p></section></aside></div>`;
}
