import { connectorCatalog, connector as connectorSpec, type AnyConnector } from './connectors/catalog.js';
import { brandMark, faviconLink } from './brand.js';
const escape = (value: unknown) => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const names = Object.fromEntries(Object.entries(connectorCatalog).map(([n, p]) => [n, p.label])) as Record<string,string>;
/** Built-in label, or a custom server's (its definition is loaded before a callback is handled). */
const label = (name: string) => names[name] ?? (() => { try { return connectorSpec(name as AnyConnector).label; } catch { return name; } })();
const style = `:root{color-scheme:light;--paper:#fafafa;--ink:#202127;--muted:#70737d;--line:#e5e6ea;--blue:#4358df;--white:#fff}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:14px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}header{max-width:1056px;margin:auto;padding:30px 28px;display:flex;align-items:center;gap:12px}header a{color:var(--ink);text-decoration:none;font:600 21px/1.2 "Avenir Next",sans-serif;letter-spacing:-.5px}.brand{display:inline-flex;align-items:center;gap:8px}.brand-mark{display:block;flex-shrink:0;width:29px;height:29px;color:var(--blue);transform:translateY(-1px)}main{max-width:720px;margin:60px auto;padding:0 28px 60px}.eyebrow{font:12px/1.4 monospace;letter-spacing:2px;color:var(--muted);text-transform:uppercase}h1{font:600 clamp(28px,5vw,38px)/1.1 "Avenir Next",-apple-system,sans-serif;letter-spacing:-1px;margin:24px 0}p{color:var(--muted);margin:16px 0}.panel{background:var(--white);border:1px solid var(--line);border-radius:10px;padding:24px;margin:28px 0}.panel p:first-child{margin-top:0}.button,button{display:inline-block;background:var(--blue);color:#fff;padding:9px 16px;border:0;border-radius:8px;font:inherit;font-weight:600;text-decoration:none;cursor:pointer}a{color:var(--blue);text-underline-offset:3px}a:focus-visible,button:focus-visible{outline:3px solid var(--blue);outline-offset:5px}.secondary{display:block;margin-bottom:22px}small{display:block;color:var(--muted);font-size:13px;margin-top:24px}code{font-size:13px;overflow-wrap:anywhere}footer{border-top:1px solid var(--line);padding-top:18px;color:var(--muted);font-size:13px}@media(max-width:520px){main{margin-top:28px}.panel{padding:22px}}`;
export function page(title: string, content: string) { return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${escape(title)} · Connany</title>${faviconLink}<style>${style}</style></head><body><header><a class="brand" href="/">${brandMark}<span>connany</span></a></header><main>${content}<footer>由 Connany 管理连接 · 你可以随时在 agent 中断开连接</footer></main></body></html>`; }
export function toolSyncPage(connector: string, error: string | null, toolCount: number) {
  return page(error ? '同步未完成' : '工具目录已同步', `<div class="eyebrow">${escape(names[connector])}</div><h1>${error ? '同步未完成' : '工具目录已同步'}</h1><div class="panel"><p>${error ? '没有更新工具目录，请回到管理后台重试。' : `已同步 ${toolCount} 个工具。本次授权仅用于读取工具目录，凭证已撤销，没有创建用户连接。`}</p>${error ? `<small>错误代码：<code>${escape(error)}</code></small>` : ''}<a class="button" href="/admin/connectors">返回管理后台 →</a></div>`);
}
/** `agent_name`: the app that created the session (e.g. Codex through MCP); users go back there. */
export function resultPage(session: any, error: string | null, access: { label: string; url: string } | null) {
  let returnUrl: string | undefined;
  if (session.return_url) { const url = new URL(session.return_url); url.searchParams.set('connany_session_id', session.id); returnUrl = url.toString(); }
  const agent = escape(session.agent_name || 'agent');
  const done = session.agent_name ? `回到 ${agent} 继续对话即可，${agent} 会接着完成你的请求。` : '你可以回到 agent，使用已授权的连接。';
  return page(error ? '连接未完成' : '已连接', `<div class="eyebrow">${escape(label(session.connector))}</div><h1>${error ? '连接未完成' : '账号已连接'}</h1><div class="panel"><p>${error ? `请回到 ${agent} 重新发起连接。若你取消了授权，可以在准备好后再试。` : access ? `账号已连接，还需要授权可访问的资源（${escape(access.label)}）。你可以现在添加，也可以返回 ${agent} 后再添加。` : done}</p>${error ? `<small>错误代码：<code>${escape(error)}</code></small>` : ''}${access ? `<a class="secondary" href="${escape(access.url)}" target="_blank" rel="noopener noreferrer">${escape(access.label)} ↗</a>` : ''}${returnUrl ? `<a class="button" href="${escape(returnUrl)}">返回 ${agent} →</a>` : `<p>现在可以关闭此页面。</p>`}</div>`);
}
export function errorPage(message: string) { return page('无法继续连接', `<h1>无法继续连接</h1><div class="panel"><p>${escape(message)}</p><p>返回 agent，重新生成一个连接链接。</p></div>`); }

export function redirectPage(url: string) { return page('正在前往授权', `<div class="eyebrow">继续连接</div><h1>正在打开授权页面</h1><p>如果浏览器没有自动跳转，请点击下方按钮。</p><a class="button" href="${escape(url)}">继续授权 →</a>`); }
